It is no longer necessary to type the output name of the source bpm file

diff --git a/bpm-package b/bpm-package
--- a/bpm-package
+++ b/bpm-package
@@ -1,9 +1,4 @@
 #!/bin/bash
-if [ $# -eq 0 ]
-then
-  echo "No output package name given!"
-  exit 1
-fi
 
 if [ -f .compilation-options ]; then
   source ./.compilation-options
@@ -20,9 +15,19 @@ while getopts "cskfa:" flag; do
   esac
 done
 
-output="${@:$OPTIND:1}"
+if [ -f pkg.info ]; then
+  echo "pkg.info file found"
+else
+  echo "pkg.info file not found in $PWD"
+  exit 1
+fi
 
-if [[ ! "$output" =~ ^[a-z.A-Z0-9_-]{1,}$ ]]; then
+output="${@:$OPTIND:1}"
+if [ -z "$output" ]; then
+  pkgname=$(grep "^name: " pkg.info)
+  output=$(echo "$pkgname" | cut -d' ' -f2)"-src.bpm"
+fi
+if [ -z "$output" ] || [[ ! "$output" =~ ^[a-z.A-Z0-9_-]{1,}$ ]]; then
   echo "Invalid output name! The name must only contain letters, numbers, hyphens or underscores!"
   exit 1
 fi
@@ -70,13 +75,6 @@ else
     echo "files/ directory or source.sh file not found in $PWD"
     exit 1
   fi
-fi
-
-if [ -f pkg.info ]; then
-  echo "pkg.info file found"
-else
-  echo "pkg.info file not found in $PWD"
-  exit 1
 fi
 
 for pkginfo in ./pkg.inf*; do
